config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  get "top" => "tasks#index"
  get "new" => "tasks#new"
  get "edit/:id" => "tasks#edit"
  get "show/:id" => "tasks#show"
  post "confirm" => "tasks#confirm"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.order(created_at: :desc)
  end

  def new
    @task = Task.new
  end

  def confirm
    @task = Task.new(task_params) 
    if @task.invalid? 
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def cast_to_bool(value)
    ActiveRecord::Type::Boolean.new.cast(value)
  end

  def create
    @task = Task.create(task_params)
    if cast_to_bool(task_params[:completed])
    end
    logger.debug("task -------------")
    logger.debug(task_params[:completed].class)

    # redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:content , :description, :completed )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h1>Tasks</h1>
    <h2>Title Descriotion Is done</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/confirm.html.erb
<h1>新規タスク 確認</h1>

<%= form_for(@task) do |t| %>
<div>
  <%= t.label :content %><br>
  <%= @task.content =%>
  
</div>
<div>
  <%= t.label :description %><br>
  <%= @task.description =%>
</div>
<div>
 <%= t.label :completed %><br>
 <%= @task.completed =%>
</div>
<div>
  <%= t.submit '新規登録' ,name: 'send'%>
</div>
<% end %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= form_for(@task) do |t| %>
  <div><%= t.label :content %></div>
  <div><%= t.text_field :content %></div>
  <div><%= t.label :description %></div>
  <div><%= t.text_field :description %></div>
  <div><%= t.label :completed %></div>
  <div><%= t.check_box :completed %></div>
  <div><%= t.submit %></div>
<% end %>
<%= link_to '戻る', "/tasks" %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<table>
  <thead>
    <tr>
      <th>タスク名</th>
      <th>内容</th>
      <th>Is done</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content =%></td>
        <td><%= task.description =%></td>
        <td><%= task.completed =%></td>
        <td><%= link_to "詳細" , task_path(task) %></td>
        <td><%= link_to "編集", edit_task_path(task) %></td>
        <td><%= link_to "削除", task_path(task), method: :delete , data: {confirm: "本当に削除しますか？"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "新規投稿","/new"  %>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

 <%= form_for @task, url: {controller: 'tasks', action: 'confirm'} do |t| %>

<div>
  <%= t.label :content %><br>
  <%= t.text_field :content %>
</div>
<div>
  <%= t.label :description %><br>
  <%= t.text_field :description %>
</div>
<div>
 <%= t.label :completed %><br>
 <%= t.check_box :completed %>
</div>
 <div>
  <%= t.submit :確認画面へ %>
</div>
<% end %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<p>Title: <%= @task.content %></p>
<p>Description: <%= @task.description %></p>

<%= link_to "一覧へ戻る", "/tasks" %>

<%= link_to '編集ページへ', edit_task_path(@task) %>